/*
  node Kindle2Anki.js --vocab vocab.db --dict dict.rawml
*/

const path = require('path')
const yargs = require('yargs')
const { existsSync } = require('fs')
const { createDictDatabase } = require('./createDictDatabase')
const { createAPKG } = require('./createAPKG')

const args = yargs
  .option('dict', {
    alias: 'd',
    describe: 'Specify the dict rawml file generated by libmobi.'
  })
  .option('vocab', {
    alias: 'v',
    describe: 'Specify the Vocabulary Builder file (vocab.db) in Kindle'
  })
  .demandOption(['dict', 'vocab']).argv

const DICT_DB = path.join(__dirname, 'dict.db')

if (!existsSync(DICT_DB)) {
  createDictDatabase({
    input: args.dict,
    output: DICT_DB
  })
}

createAPKG({
  vocab: args.vocab,
  dict: DICT_DB
})
