/*
  node Kindle2Anki.js --vocab=vocab.db --dict=dict.rawml
*/

const path = require('path')
const yargs = require('yargs')
const { APKG } = require('anki-apkg')
const { createDictDatabase } = require('./createDictDatabase')

let args = yargs
  .option('dict', {
    alias: 'd',
    describe: 'Specify the dict rawml file generated by libmobi.'
  })
  .option('vocab', {
    alias: 'v',
    describe: 'Specify the Vocabulary Builder file (vocab.db) in Kindle'
  })
  .demandOption(['vocab']).argv

createDictDatabase({
  input: args.dict,
  output: path.join(__dirname, 'dict.db')
})
// const sqlite3 = require('sqlite3').verbose()
// const db = new sqlite3.Database(args.vocab, err => {
//   if (err) {
//     return console.log('OPEN vocab.db ERROR:', err.message)
//   }
// })
// db.all('SELECT title from BOOK_INFO', (err, rows) => {
//   if (err) {
//     return console.error('QUERY vocab.db ERROR', err.message)
//   }
//   rows.forEach(row => {
//     console.log(row.title)
//   })
// })
